* Convert Images

   convert 02_native.jpg -type Grayscale 1.jpg
   
   convert 1.jpg -threshold 50% 2.jpg

   for i in *.jpg; do convert "$i" -type Grayscale "${i%.jpg}_gray.jpg"; done

   for i in *gray.jpg; do convert "$i" -threshold 50% "${i%.jpg}_bw.jpg"; done

* Bao Juan 寶卷 Collection

  1. [ ] *正信除疑無修證自在寳卷 Zheng xin chu yi wu xiu zheng zi zai bao juan*

     羅淸. /正信除疑無修證自在寳卷 / [羅淸撰]. /明刻本. /經摺裝. /半頁4行13字. 前有扉畫, 后有韋陀合十圖. /Luo, Qing. / 明刻本. /Ming ke ben. / [China : s.n.

  2. [ ] *嘆世無為經 Tan shi wu wei jing*

     羅淸. /嘆世無為經 / [羅淸撰]. /嘆世無為寳卷 /嘆世寳卷 /無為寳卷 /明刻本. /經摺裝. /半頁4行13字至15字. 前有扉畫, 后有韋陀合十圖. /Luo, Qing. / 明刻本. /Ming ke ben. / [China : s.n.

* Chinese Rare Books- Unique, Manuscripts, ect. 哈佛燕京圖書館中文善本特藏 稿,钞,孤本(傅斯年圖書館合作項目) 

  1. [X] *簡文編 : 五卷 Jian wen bian : 5 juan*

     簡文編 : 五卷 / 伍袁萃編輯 錢紹起校. /[China] : 吳縣伍毓耆, 伍毓昚貽安堂, 明萬曆丁未 [35年, 1607] /是書為彙古書史中言簡而有文者為一編. /Seal: "世秀之印". /九行二十二字, 四周單邊, 白口, 單魚尾, 書口下刋"貽安堂", 框高 20.9 x 11.5公分. /伍袁萃, jin shi 1580, ed. /錢紹起. / [China] : Wuxian Wu Yuqi, Wu Yushen Yi an tang (1607)

  2. [ ] *飛霞館選百家纂雋 : 10卷 Fei xia guan xuan Bai jia zuan jun : 10 juan*

     飛霞館選百家纂雋 : 10卷 / 陸孝錫編選. /百家纂雋 /[China] : 陸孝錫, 明萬曆 [i.e. between 1573 and 1620] /九行二十字, 四周單邊, 白口, 無魚尾, 框高 21.3 x 12.9. /陸孝錫. / [China] : Lu Xiaoxi (1573)

  3. [X] *醒夢駢言 : 12回. Xing meng pian yan :12 hui*

     醒夢駢言 : 12回. [Microform] / 菊畦主人偶輯. /[China : s.n.], [淸初 between 1644 and 1735] /原刋本. /卷末有藏者齊如山親筆跋語两則. /Juqizi, active 17th century. / [China : s.n.] (1644)

  4. [X] *新鐫註釋里居通用合璧文翰 : 二卷 Xin juan zhu shi Li ju tong yong he bi wen han : 2 juan*

     新鐫註釋里居通用合璧文翰 : 二卷 / 屠隆編選 俞啟相校正. /里居通用合璧文翰 /[China] : 建邑書林種德堂熊雲吾, 明萬曆 [i.e. between 1573 and 1620] /十行十八字, 上欄十六行九字, 四周單邊, 白口, 雙魚尾, 框高 20.9 x 12.3. /卷二有牌記, 刋「書林種德堂熊氏雲吾繡梓行」 /Seal: "殘花書屋". /屠隆, 1542-1605, comp. /俞啟相, 校正. /熊雲吾, 刋. /種德堂, 刋. / [China] : Jianyi Shulin Zhong de tang Xiong Yunwu (1573)

  5. [X] *新箋決科古今源流至論 : 前集十卷, 後集十卷, 續集十卷, 別集十卷 Xin jian jue ke gu jin yuan liu zhi lun : qian ji 10 juan, hou ji 10 juan, xu ji 10 juan, bie ji 10 juan*

     新箋決科古今源流至論 : 前集十卷, 後集十卷, 續集十卷, 別集十卷 / 林駉撰 黃履翁編別集. /古今源流至論 /[China : 建陽書林詹氏刻本, 明宣德2年[1427] /十三行二八字, 四周雙邊, 黑口, 雙魚尾, 框高19.8 x 12.9. /Seals: "旡竟先生獨志堂物", "咸豐庚申以後攷藏" [... et al.]. /著錄: 中國古籍善本書目. /林駉, 編. /黃履翁, jin shi 1232, 編. / [China : Jianyang shu lin Zhan shi e ben (1465)

  6. [X] *投桃記 : 二卷 Tou tao ji : er juan*

     汪廷訥, active 16th century-17th century. /投桃記 : 二卷 / 汪廷訥著. /環翠堂新編投桃記 /精鈔本. /[China] : 立承, [民國間, between 1911 and 1953] /10 行 20 字, 四周單欄白口單魚尾, 框 21.5 x 13.9 公分. /卷前有目錄, 目錄題名"環翠堂新編投桃記". /有精繪插圖. /中國國家圖書館有明汪氏刻《環翠堂樂府投桃記》二卷, 《古本戲曲叢刊》二集亦收錄. /有"齊林玉世世子孫永寶用"朱長方, "高陽齊氏百金齋存書之印"朱方, "齊氏所藏戲曲小說印"白方, "王立承"白方, "立承寫定"朱方, "如山讀過"白方, "鳴晦盧珍藏金石書畫記"朱長方印. /Wang, Tingne, active 16th century-17th century. / 精鈔本. /Jing chao ben. / [China] : Licheng (1911)

  7. [X] *(新編)西川圖 : 30齣. (Xin bian) xi chuan tu :30 chu*

     洪昇, 1645-1704. /(新編)西川圖 : 30齣. [Microform] / 洪昇撰. /西川圖 /[China : s.n.], 淸咸豐9 [1859] /鈔本. /簽題: 新編西川圖傳, 奇味冰之曲. /Hong, Sheng, 1645-1704. / [China : s.n.] (1859)

  8. [X] *新刻友花居上林鴻 : 四卷 Xin ke You hua ju shang lin hong : 4 juan*

     新刻友花居上林鴻 : 四卷 / 鍾惺編輯 陳仁錫較. /友花居上林鴻 /上林鴻 /[China : s.n., 明末 i.e. between 1621 and 1644] /十行十六字, 上欄十二行十字, 四周單邊, 白口, 無魚尾, 框高 19.6 x 11.9. /Seals: "碧梧亭藏書印" [... et al.]. /鍾惺, 1574-1625, 編輯. /陳仁錫, 1581-1636, 較. / [China : s.n. (1621)

  9. [X] *汪氏珊瑚網法書題跋 : 二十四卷 Wang shi shan hu wang fa shu ti ba : er shi si juan*

     汪砢玉, 1587- /汪氏珊瑚網法書題跋 : 二十四卷 / [汪砢玉撰] /鈔本. /[China : s.n., 淸, between 1644 and 1911] /10行20字, 無格. /Wang, Luoyu, 1587- / 鈔本. /Chao ben. / [China : s.n. (1644)

  10. [X] *鼎鐫潄石山房彙編註釋士民便觀雲箋柬 : 四卷 Ding juan Shu shi shan fang hui bian zhu shi shi min bian guan yun jian jian : 4 juan*

      鼎鐫潄石山房彙編註釋士民便觀雲箋柬 : 四卷 / 陳翊九彙編. /雲箋柬 /二刻翰墨琅[han] /翰墨琅[han] /[China] : 四知館, [明末 i.e. between 1621 and 1644] /九行十八字, 上欄十一行十字, 四周單邊, 白口, 無魚尾, 框高 20.5 x 11.7. /書名頁題: (二刻)「翰墨琅函 ... 四知館梓」 /Seal: "天橋文庫". /陳翊九, 彙編. /四知館, 刋. / [China] : Si zhi guan (1621)

  11. [X] *[唐詩韻選] [Tang shi yun xuan]*

      [唐詩韻選] / 桂雪芸[選輯]. /[China : s.n.], 清道光30 [1850] 序. /桂雪芸, active 1850, [選輯] / [China : s.n.] (1850)

  12. [X] *檇李曹太史評鐫古今全史一覽 : 6卷 Zuili Cao tai shi ping juan Gu jin quan shi yi lan : 6 juan*
      舒弘諤, active 1641. /檇李曹太史評鐫古今全史一覽 : 6卷 / 舒弘諤撰 曹勳評. /古今全史一覽 /[China] : 檇李曹氏, 明崇禎辛丑[14年, 1641] /十行二六字, 四周單邊, 白口, 無魚尾, 眉端刻評, 框高 21.1 x 11.7. /曹勳. /Shu, Hong'e, active 1641. / [China] : Zuili Cao shi (1641)

  13. [X] *新刻全補評註文豹金璧故事 : 四卷 Xin ke quan bu ping zhu wen bao Jin bi gu shi : 4 juan*
      新刻全補評註文豹金璧故事 : 四卷 / [鄭以偉編]. /金璧故事 /[China], 明 [between 1465 and 1620] /十一行二三字, 四周單邊, 白口, 無魚尾, 眉端上刻評, 框高 20.5 x 11.8. /Seals: "詩政堂暴書", "至誠堂". /鄭以偉, -1633, 編. / [China] (1465)

  14. [X] *新板增補天下便用文林妙錦萬寶全書 : 三八卷 Xin ban zeng bu tian xia bian yong wen lin miao jin Wan bao quan shu : 38 juan*
      新板增補天下便用文林妙錦萬寶全書 : 三八卷 / 劉雙松[子明] 删補重編. /萬寶全書 /書口題: 真萬寶全書 /全補文林妙錦萬寶全書 /[China] : 書林安正堂劉雙松, 明萬曆壬子 [40年, 1612] /上欄十六行十四字, 下欄十四行十八字, 四周雙邊, 白口, 單魚尾, 框高 19.9 x 12.2. /扉頁題: 全補文林妙錦萬寶全書 ... 書林安正堂劉雙松重梓. /Seals: "半澤文庫" [... et al]. /著錄: 中國古籍善本書目. /劉子明, active 1612, ed. /安正堂, 刋. / [China] : Shulin An zheng tang Liu Shuangsong (1612)

  15. [ ] *南城召對 Nan cheng zhao dui*
      南城召對 / 明世宗, 李時等對語. /[China : s.n.], 明 [between 1465 and 1620] /藍格紙抄本. /十行二三字. /首有官防印模糊不清, 封面有「乾隆三十八年十一月浙江巡撫三寶送到范懋柱家藏南城召對壹部計書堂本」呈繳印. /Seals: "宗室聖昱臧圖書印", "燕京大學圖書館" [... et al.]. /明世宗, Emperor of China, 1507-1566. /李時. / [China : s.n.] (1465)

  16. [ ] *詩學集成押韻淵海 : 二十卷 Shi xue ji cheng ya yun yuan hai : 20 juan*
      詩學集成押韻淵海 : 二十卷 / 嚴毅編輯. /書明亦有題: 新編詩學集成押韻淵海 /[China] : 新安余氏, 明成化甲午 [10年, 1474] /重新刋本. /十二行十四字不等, 四周雙邊, 黑口, 雙魚尾, 框高19.1 x 12.1. /卷二十末有牌記刋「明成化甲午新安余氏重新刋行」 /嚴毅, active 14th century, 編輯. / [China] : Xin'an Yu shi (1474)

  17. [X] *事物紀原集類 : 十卷 Shi wu ji yuan ji lei : shi juan*
      高承, active 11th century. /事物紀原集類 : 十卷 / [高承撰] 閻敬校正. /鈔本. /[China : s.n., 淸, between 1662 and 1736] /8行18字. /未諱"曆"字. 有"莫繩孫字仲武" "莫有芝圖書印". /閻敬, ju ren 1444, ed. /Gao, Cheng, active 11th century. / 鈔本. /Chao ben. / [China : s.n. (1662)

  18. [X] *牧齋紅豆庄雜錄 : 三卷 Muzhai Hong dou zhuang za lu : san juan*
      錢謙益, 1582-1664. /牧齋紅豆庄雜錄 : 三卷 / [錢謙益撰]. /鈔本. /[China : s.n., 淸, between 1662 and 1795] /8行16字, 黑格. /"玄"字已諱. /Qian, Qianyi, 1582-1664. / 鈔本. /Chao ben. / [China : s.n. (1662)

  19. [X] *空同詩鈔 : 十六卷, 附錄 Kong tong shi chao : shi liu juan, fu lu*
      李夢陽, 1472-1529. /空同詩鈔 : 十六卷, 附錄 / 李夢陽撰 桑調元編. /鈔本. /[China : s.n., 淸, between 1821 and 1911] /10行21字. /據清乾隆間刻本所鈔. /桑調元, 1695-1771 /Li, Mengyang, 1472-1529. / 鈔本. /Chao ben. / [China : s.n. (1821)

  20. [X] *圍爐詩話 : 六卷 Wei lu shi hua : liu juan*
      吳喬. /圍爐詩話 : 六卷 / 吳喬撰. /鈔本. /[China : s.n., 淸, between 1736 and 1821] /9行25字. /有"翁方綱" "雨山艸堂" "梧門詩草" "詩龕書畫印"等印. /Wu, Shu, active 17th century. / 鈔本. /Chao ben. / [China : s.n. (1736)

  21. 
